name: Generate Tetris Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: Guilhermeeduardo
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
